added quicksort in c++ language and edited readme
Himanshu40/Sorting-Algorithm pull request #13
Opened 2020-10-08 06:57 UTC by Jaidev2001

Quicksort program added in c++ language and edited readme with proper describing of algorithm in steps. :smile:

2020-10-09 04:44 UTC, Himanshu40 commented
Reference to #12 #3

2020-10-09 14:41 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +    int arr[] = {10, 7, 8, 9, 1, 5};
```suggestion
    
```

2020-10-09 14:43 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +    int arr[] = {10, 7, 8, 9, 1, 5};
```suggestion
    Take run-time input instead of giving static input
```

2020-10-09 14:52 UTC, Himanshu40 requested changes
1. Remove unusual or excess new lines in each function.
2. Take run-time input rather than static or hard-coded input.

2020-10-09 14:52 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +    int arr[] = {10, 7, 8, 9, 1, 5};
Take run-time input rather than static input or hard-coded input.

2020-10-09 14:52 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +        //i++;
```suggestion
```

2020-10-09 14:52 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +    return (i + 1);
```suggestion

    return (i + 1);  
```

2020-10-09 14:52 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +
```suggestion
```

2020-10-09 14:52 UTC, Himanshu40 commented on Quick_Sort/quicksort.cpp
> +
```suggestion
```

2020-10-09 15:00 UTC, Himanshu40 requested changes
1. Add a table and you can see github markdown style on how to add a table or for reference you can see my BubbleSort/README.md where I used a table.

2020-10-09 15:02 UTC, Himanshu40 commented
I have left some comments on your commits. Have a look !!

2020-10-10 07:26 UTC, Jaidev2001 reviewed
Hey, i have edited and make the changes that are required.

2020-10-10 17:10 UTC, Himanshu40 commented
The output of Quick Sort is not expected like the following:-
```
Himanshu@PREDATOR-HELIOS-300 MINGW64 ~/Desktop
$ ./run.exe

        ---QUICK SORT---
Enter the size of the array: 10
Enter the elements of array:
9
8
7
6
5
4
3
2
1
0

Elements in the array: 9 8 7 6 5 4 3 2 1 0
Elements in ascending order:
0 0 1 2 3 4 5 6 7 8
```
Why there is an extra 0 at the start @Jaidev2001 ?

2020-10-10 17:40 UTC, Jaidev2001 reviewed
:smile:

2021-09-24 06:18 UTC, closed without merging